# Generated by Django 5.2.4 on 2025-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("tag", models.CharField(max_length=100)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=0.0)),
            ],
        ),
    ]
